import Head from 'next/head';
import { Inter } from '@next/font/google';
import Hero from '@containers/Hero';
import ContainerInfo from '@containers/ContainerInfo';
import CardsContainer from '@containers/CardsContainer';
import ListIcon from '@containers/ListIcon';
import Footer from '@components/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Appist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ContainerInfo />
      <CardsContainer />
      <ListIcon />
      <Footer />
    </>
  )
}
