import Head from 'next/head';
import { Inter } from '@next/font/google';
import AppContext from '@context/AppContext';
import { useContext } from 'react';

import Hero from '@containers/Hero';
import ContainerInfo from '@containers/ContainerInfo';
import CardsContainer from '@containers/CardsContainer';
import ListIcon from '@containers/ListIcon';
import Footer from '@components/Footer';
import Menu from '@components/Menu';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {state} = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Appist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ContainerInfo />
      <CardsContainer />
      <ListIcon />
      <Footer />
      {state.isViewMenu && <Menu />}
    </>
  )
}
