import Head from 'next/head';
import AppContext from '@context/AppContext';
import { useContext } from 'react';

import Footer from '@components/Footer';
import Menu from '@components/Menu';
import DocsContainer from '@containers/DocsContainer';
import ContainerInfo from '@containers/ContainerInfo';

import useGetDocs from '@hooks/useGetDocs';

const infoOne = {
  title:'Documentos Principales',
  text: 'Acta de iniciación, documento maestro, etc.'
};

const infoTwo = {
  title:'Bitácoras',
  text: 'Todas las bitácoras de cada integrante.'
};

const infoThree = {
  title:'Resumenes de actividades',
  text: 'Todas los resumenes de actividades de cada integrante.'
};

const infoFour = {
  title:'Cuadernos de trabajo',
  text: 'Todos los cuadernos de trabajo de cada integrante.'
};

export default function Home() {
  const { state } = useContext(AppContext);
  const allDocs = useGetDocs();
  const docs = allDocs.PDocs;
  const bitacoras = allDocs.bitac;
  const RActividades = allDocs.RActividades;
  const booksJobs = allDocs.booksJobs;

  return (
    <>
      <Head>
        <title>Appist - Documentos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerInfo info={infoOne} />
      <DocsContainer docs={docs} />
      <ContainerInfo info={infoTwo} />
      <DocsContainer docs={bitacoras} />
      <ContainerInfo info={infoThree} />
      <DocsContainer docs={RActividades} />
      <ContainerInfo info={infoFour} />
      <DocsContainer docs={booksJobs} />
      <Footer />
      {state.isViewMenu && <Menu />}
    </>
  );
}
